// Auto-generated by compile-translations.js
// Do not edit this file manually - it will be overwritten

let enusMessages: { messages: string };
let ptbrMessages: { messages: string };
let esesMessages: { messages: string };
let zhtwMessages: { messages: string };
let frfrMessages: { messages: string };

try {
  // Try to import compiled translation modules
  enusMessages = require("./data/en-US/messages.js");
} catch (error) {
  console.warn("[locale-mapping] Failed to load en-US translations:", error);
  enusMessages = {
    messages:
      "# Fallback\\nloading = Loading...\\nerror = Error\\ncancel = Cancel\\nsettings-title = Settings",
  };
}

try {
  // Try to import compiled translation modules
  ptbrMessages = require("./data/pt-BR/messages.js");
} catch (error) {
  console.warn("[locale-mapping] Failed to load pt-BR translations:", error);
  ptbrMessages = {
    messages:
      "# Fallback\\nloading = Loading...\\nerror = Error\\ncancel = Cancel\\nsettings-title = Settings",
  };
}

try {
  // Try to import compiled translation modules
  esesMessages = require("./data/es-ES/messages.js");
} catch (error) {
  console.warn("[locale-mapping] Failed to load es-ES translations:", error);
  esesMessages = {
    messages:
      "# Fallback\\nloading = Loading...\\nerror = Error\\ncancel = Cancel\\nsettings-title = Settings",
  };
}

try {
  // Try to import compiled translation modules
  zhtwMessages = require("./data/zh-TW/messages.js");
} catch (error) {
  console.warn("[locale-mapping] Failed to load zh-TW translations:", error);
  zhtwMessages = {
    messages:
      "# Fallback\\nloading = Loading...\\nerror = Error\\ncancel = Cancel\\nsettings-title = Settings",
  };
}

try {
  // Try to import compiled translation modules
  frfrMessages = require("./data/fr-FR/messages.js");
} catch (error) {
  console.warn("[locale-mapping] Failed to load fr-FR translations:", error);
  frfrMessages = {
    messages:
      "# Fallback\\nloading = Loading...\\nerror = Error\\ncancel = Cancel\\nsettings-title = Settings",
  };
}

// Export locale mapping for metro-loader
export const localeMessages = {
  "en-US": enusMessages,
  "pt-BR": ptbrMessages,
  "es-ES": esesMessages,
  "zh-TW": zhtwMessages,
  "fr-FR": frfrMessages,
} as const;

export { enusMessages, esesMessages, frfrMessages, ptbrMessages, zhtwMessages };

export const supportedLocales = [
  "en-US",
  "pt-BR",
  "es-ES",
  "zh-TW",
  "fr-FR",
] as const;
export type SupportedLocale = (typeof supportedLocales)[number];

export function validateLocaleModule(
  locale: string,
  module: any,
): module is { messages: string } {
  return (
    module &&
    typeof module === "object" &&
    "messages" in module &&
    typeof module.messages === "string" &&
    module.messages.length > 0
  );
}

export function getAvailableLocales(): SupportedLocale[] {
  return supportedLocales.filter((locale) => {
    const module = localeMessages[locale];
    return validateLocaleModule(locale, module);
  });
}
