// Auto-generated by compile-translations.js
// Do not edit this file manually - it will be overwritten

import type { SupportedLocale } from "./index";

export interface LanguageInfo {
  code: SupportedLocale;
  name: string;
  nativeName: string;
  flag: string;
}

export const LANGUAGE_INFO: Record<SupportedLocale, LanguageInfo> = {
  "en-US": {
    code: "en-US",
    name: "English",
    nativeName: "English",
    flag: "🇺🇸",
  },
  "pt-BR": {
    code: "pt-BR",
    name: "Portuguese",
    nativeName: "Português",
    flag: "🇧🇷",
  },
  "es-ES": {
    code: "es-ES",
    name: "Spanish",
    nativeName: "Español",
    flag: "🇪🇸",
  },
  "zh-TW": {
    code: "zh-TW",
    name: "Chinese Traditional",
    nativeName: "繁體中文",
    flag: "🇹🇼",
  },
  "fr-FR": {
    code: "fr-FR",
    name: "French",
    nativeName: "Français",
    flag: "🇫🇷",
  },
} as const;

export const DEFAULT_TRANSLATIONS: Record<SupportedLocale, string> = {
  "en-US": `# Fallback\nloading = Loading...\nerror = Error`,
  "pt-BR": `# Fallback\nloading = Carregando...\nerror = Erro`,
  "es-ES": `# Fallback\nloading = Cargando...\nerror = Error`,
  "zh-TW": `# Fallback\nloading = 載入中...\nerror = 錯誤`,
  "fr-FR": `# Fallback\nloading = Chargement...\nerror = Erreur`,
} as const;

export function getLanguageInfo(locale: SupportedLocale): LanguageInfo {
  return LANGUAGE_INFO[locale];
}

export function getDefaultTranslation(locale: SupportedLocale): string {
  return DEFAULT_TRANSLATIONS[locale];
}

export function getAllLanguageInfo(): LanguageInfo[] {
  return Object.values(LANGUAGE_INFO);
}
