// Auto-generated by compile-translations.js
// Do not edit this file manually - it will be overwritten

import type { TranslationSource } from "../direct-provider";
import {
  dynamicActivate,
  loadAllLocales,
  loadLocale,
} from "../loaders/metro-loader";

/**
 * Load all translations dynamically from compiled .ftl files
 *
 * Usage:
 * ```tsx
 * import { loadDynamicTranslations } from './locales/translations';
 *
 * const App = () => (
 *   <DirectI18nProvider
 *     enableDynamicLoading={true}
 *     preloadAll={false} // Only load current locale
 *     debug={true}
 *   >
 *     <YourApp />
 *   </DirectI18nProvider>
 * );
 * ```
 */
export async function loadDynamicTranslations(
  debug = false,
): Promise<TranslationSource[]> {
  return loadAllLocales(debug);
}

/**
 * Load a specific locale dynamically
 * Useful for lazy loading when switching languages
 */
export async function loadDynamicLocale(
  locale: "en-US" | "pt-BR" | "es-ES" | "zh-TW" | "fr-FR",
  debug = false,
) {
  return loadLocale(locale, debug);
}

/**
 * Activate a locale dynamically (similar to Lingui's approach)
 * This loads and activates a locale in one step
 */
export async function activateLocale(
  locale: "en-US" | "pt-BR" | "es-ES" | "zh-TW" | "fr-FR",
  debug = false,
) {
  return dynamicActivate(locale, undefined, debug);
}
