// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package streamplace

// schema: place.stream.broadcast.defs

import (
	appbskytypes "github.com/bluesky-social/indigo/api/bsky"
	"github.com/bluesky-social/indigo/lex/util"
)

// BroadcastDefs_BroadcastOriginView is a "broadcastOriginView" in the place.stream.broadcast.defs schema.
type BroadcastDefs_BroadcastOriginView struct {
	Author *appbskytypes.ActorDefs_ProfileViewBasic `json:"author" cborgen:"author"`
	Cid    string                                   `json:"cid" cborgen:"cid"`
	Record *util.LexiconTypeDecoder                 `json:"record" cborgen:"record"`
	Uri    string                                   `json:"uri" cborgen:"uri"`
}
