// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package streamplace

// schema: place.stream.broadcast.origin

import (
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("place.stream.broadcast.origin", &BroadcastOrigin{})
} //
// RECORDTYPE: BroadcastOrigin
type BroadcastOrigin struct {
	LexiconTypeID string `json:"$type,const=place.stream.broadcast.origin" cborgen:"$type,const=place.stream.broadcast.origin"`
	// broadcaster: did of the broadcaster that operates the server syndicating the livestream
	Broadcaster *string `json:"broadcaster,omitempty" cborgen:"broadcaster,omitempty"`
	// irohTicket: Iroh ticket that can be used to access the livestream from the server
	IrohTicket *string `json:"irohTicket,omitempty" cborgen:"irohTicket,omitempty"`
	// server: did of the server that's currently rebroadcasting the livestream
	Server string `json:"server" cborgen:"server"`
	// streamer: DID of the streamer whose livestream is being published
	Streamer string `json:"streamer" cborgen:"streamer"`
	// updatedAt: Periodically updated timestamp when this origin last saw a livestream
	UpdatedAt string `json:"updatedAt" cborgen:"updatedAt"`
}
