// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package streamplace

// schema: place.stream.chat.defs

import (
	"encoding/json"
	"fmt"

	appbskytypes "github.com/bluesky-social/indigo/api/bsky"
	"github.com/bluesky-social/indigo/lex/util"
)

// ChatDefs_MessageView is a "messageView" in the place.stream.chat.defs schema.
//
// RECORDTYPE: ChatDefs_MessageView
type ChatDefs_MessageView struct {
	LexiconTypeID string                                   `json:"$type,const=place.stream.chat.defs#messageView" cborgen:"$type,const=place.stream.chat.defs#messageView"`
	Author        *appbskytypes.ActorDefs_ProfileViewBasic `json:"author" cborgen:"author"`
	ChatProfile   *ChatProfile                             `json:"chatProfile,omitempty" cborgen:"chatProfile,omitempty"`
	Cid           string                                   `json:"cid" cborgen:"cid"`
	// deleted: If true, this message has been deleted or labeled and should be cleared from the cache
	Deleted   *bool                         `json:"deleted,omitempty" cborgen:"deleted,omitempty"`
	IndexedAt string                        `json:"indexedAt" cborgen:"indexedAt"`
	Record    *util.LexiconTypeDecoder      `json:"record" cborgen:"record"`
	ReplyTo   *ChatDefs_MessageView_ReplyTo `json:"replyTo,omitempty" cborgen:"replyTo,omitempty"`
	Uri       string                        `json:"uri" cborgen:"uri"`
}

type ChatDefs_MessageView_ReplyTo struct {
	ChatDefs_MessageView *ChatDefs_MessageView
}

func (t *ChatDefs_MessageView_ReplyTo) MarshalJSON() ([]byte, error) {
	if t.ChatDefs_MessageView != nil {
		t.ChatDefs_MessageView.LexiconTypeID = "place.stream.chat.defs#messageView"
		return json.Marshal(t.ChatDefs_MessageView)
	}
	return nil, fmt.Errorf("cannot marshal empty enum")
}
func (t *ChatDefs_MessageView_ReplyTo) UnmarshalJSON(b []byte) error {
	typ, err := util.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "place.stream.chat.defs#messageView":
		t.ChatDefs_MessageView = new(ChatDefs_MessageView)
		return json.Unmarshal(b, t.ChatDefs_MessageView)

	default:
		return nil
	}
}
