// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package streamplace

// schema: place.stream.chat.block

import (
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("place.stream.chat.block", &ChatBlock{})
} //
// RECORDTYPE: ChatBlock
type ChatBlock struct {
	LexiconTypeID string `json:"$type,const=place.stream.chat.block" cborgen:"$type,const=place.stream.chat.block"`
	// createdAt: Client-declared timestamp when this block was created.
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
	// expiresAt: Optional timestamp when this block expires. If omitted, the block is permanent.
	ExpiresAt *string `json:"expiresAt,omitempty" cborgen:"expiresAt,omitempty"`
	// reason: Optional reason for the block.
	Reason *string `json:"reason,omitempty" cborgen:"reason,omitempty"`
	// streamer: The DID of the streamer whose chat this block applies to.
	Streamer string `json:"streamer" cborgen:"streamer"`
	// subject: The DID of the user being blocked from chat.
	Subject string `json:"subject" cborgen:"subject"`
}
