// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package streamplace

// schema: place.stream.chat.hide

import (
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("place.stream.chat.hide", &ChatHide{})
} //
// RECORDTYPE: ChatHide
type ChatHide struct {
	LexiconTypeID string `json:"$type,const=place.stream.chat.hide" cborgen:"$type,const=place.stream.chat.hide"`
	// hiddenMessage: URI of the hidden chat message.
	HiddenMessage string `json:"hiddenMessage" cborgen:"hiddenMessage"`
}
