// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package streamplace

// schema: place.stream.chat.moderator

import (
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("place.stream.chat.moderator", &ChatModerator{})
} //
// RECORDTYPE: ChatModerator
type ChatModerator struct {
	LexiconTypeID string `json:"$type,const=place.stream.chat.moderator" cborgen:"$type,const=place.stream.chat.moderator"`
	// createdAt: Client-declared timestamp when this moderator was added.
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
	// moderator: The DID of the user granted moderator permissions.
	Moderator string `json:"moderator" cborgen:"moderator"`
	// permissions: Array of permissions granted to this moderator. Note: 'ban' covers both permanent bans and temporary timeouts (via expiresAt field).
	Permissions []string `json:"permissions" cborgen:"permissions"`
}
