// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package streamplace

// schema: place.stream.default.metadata

import (
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("place.stream.default.metadata", &DefaultMetadata{})
} //
// RECORDTYPE: DefaultMetadata
type DefaultMetadata struct {
	LexiconTypeID string `json:"$type,const=place.stream.default.metadata" cborgen:"$type,const=place.stream.default.metadata"`
	// contentWarnings: Content warnings for this stream.
	ContentWarnings    []string                            `json:"contentWarnings,omitempty" cborgen:"contentWarnings,omitempty"`
	DistributionPolicy *DefaultMetadata_DistributionPolicy `json:"distributionPolicy,omitempty" cborgen:"distributionPolicy,omitempty"`
	Rights             *DefaultMetadata_Rights             `json:"rights,omitempty" cborgen:"rights,omitempty"`
}

// DefaultMetadata_DistributionPolicy is a "distributionPolicy" in the place.stream.default.metadata schema.
//
// Distribution and rebroadcast policy.
type DefaultMetadata_DistributionPolicy struct {
	// allowArchive: Whether nodes can archive this stream.
	AllowArchive *bool `json:"allowArchive,omitempty" cborgen:"allowArchive,omitempty"`
	// broadcastUntil: When rebroadcast permissions expire (ISO 8601 format). If not specified, no rebroadcast allowed.
	BroadcastUntil *string `json:"broadcastUntil,omitempty" cborgen:"broadcastUntil,omitempty"`
}

// DefaultMetadata_Rights is a "rights" in the place.stream.default.metadata schema.
//
// Content rights and attribution information
type DefaultMetadata_Rights struct {
	// attribution: Attribution name or handle.
	Attribution *string `json:"attribution,omitempty" cborgen:"attribution,omitempty"`
	// license: License identifier (e.g. 'CC BY-NC-SA', 'All Rights Reserved').
	License *string `json:"license,omitempty" cborgen:"license,omitempty"`
	// usageTerms: Additional notice or usage terms.
	UsageTerms *string `json:"usageTerms,omitempty" cborgen:"usageTerms,omitempty"`
	// year: Year of creation or publication (e.g. '2025').
	Year *string `json:"year,omitempty" cborgen:"year,omitempty"`
}
