// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package streamplace

// schema: place.stream.default.metadata

import (
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("place.stream.default.metadata", &DefaultMetadata{})
} //
// RECORDTYPE: DefaultMetadata
type DefaultMetadata struct {
	LexiconTypeID string                         `json:"$type,const=place.stream.default.metadata" cborgen:"$type,const=place.stream.default.metadata"`
	ContentRights *DefaultMetadata_ContentRights `json:"contentRights,omitempty" cborgen:"contentRights,omitempty"`
	// contentWarnings: Content warnings for this stream.
	ContentWarnings    []string                            `json:"contentWarnings,omitempty" cborgen:"contentWarnings,omitempty"`
	DistributionPolicy *DefaultMetadata_DistributionPolicy `json:"distributionPolicy,omitempty" cborgen:"distributionPolicy,omitempty"`
}

// DefaultMetadata_ContentRights is a "contentRights" in the place.stream.default.metadata schema.
//
// Content rights and attribution information.
type DefaultMetadata_ContentRights struct {
	// copyrightNotice: Copyright notice for the work.
	CopyrightNotice *string `json:"copyrightNotice,omitempty" cborgen:"copyrightNotice,omitempty"`
	// copyrightYear: Year of creation or publication.
	CopyrightYear *int64 `json:"copyrightYear,omitempty" cborgen:"copyrightYear,omitempty"`
	// creator: Name of the creator of the work.
	Creator *string `json:"creator,omitempty" cborgen:"creator,omitempty"`
	// creditLine: Credit line for the work.
	CreditLine *string `json:"creditLine,omitempty" cborgen:"creditLine,omitempty"`
	// license: License URL or identifier.
	License *string `json:"license,omitempty" cborgen:"license,omitempty"`
}

// DefaultMetadata_DistributionPolicy is a "distributionPolicy" in the place.stream.default.metadata schema.
//
// Distribution and rebroadcast policy.
type DefaultMetadata_DistributionPolicy struct {
	// allowArchive: Whether nodes can archive this stream.
	AllowArchive *bool `json:"allowArchive,omitempty" cborgen:"allowArchive,omitempty"`
	// broadcastExpiry: When rebroadcast permissions expire. If not specified, there is no expiration on rebroadcast permission.
	BroadcastExpiry *string `json:"broadcastExpiry,omitempty" cborgen:"broadcastExpiry,omitempty"`
}
