// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package streamplace

// schema: place.stream.live.recommendations

import (
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("place.stream.live.recommendations", &LiveRecommendations{})
} //
// RECORDTYPE: LiveRecommendations
type LiveRecommendations struct {
	LexiconTypeID string `json:"$type,const=place.stream.live.recommendations" cborgen:"$type,const=place.stream.live.recommendations"`
	// createdAt: Client-declared timestamp when this list was created.
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
	// streamers: Ordered list of recommended streamer DIDs
	Streamers []string `json:"streamers" cborgen:"streamers"`
}
