// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package streamplace

// schema: place.stream.live.metadata

import (
	comatprototypes "github.com/bluesky-social/indigo/api/atproto"
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("place.stream.live.metadata", &LiveMetadata{})
} //
// RECORDTYPE: LiveMetadata
type LiveMetadata struct {
	LexiconTypeID string             `json:"$type,const=place.stream.live.metadata" cborgen:"$type,const=place.stream.live.metadata"`
	C2pa          *LiveMetadata_C2pa `json:"c2pa,omitempty" cborgen:"c2pa,omitempty"`
	// contentWarningScheme: controlled vocabulary scheme uri.
	ContentWarningScheme *string `json:"contentWarningScheme,omitempty" cborgen:"contentWarningScheme,omitempty"`
	// contentWarningUris: uris from iptc content warning vocabulary (https://cv.iptc.org/newscodes/contentwarning/). these are written into c2pa.
	ContentWarningUris []string `json:"contentWarningUris,omitempty" cborgen:"contentWarningUris,omitempty"`
	// contentWarnings: prefer contentWarningUris as it maps to iptc uris.
	ContentWarnings []string `json:"contentWarnings,omitempty" cborgen:"contentWarnings,omitempty"`
	// createdAt: iso 8601 with timezone; mirrored to c2pa.metadata (dc:created/xmp:CreateDate).
	CreatedAt          string                           `json:"createdAt" cborgen:"createdAt"`
	DistributionPolicy *LiveMetadata_DistributionPolicy `json:"distributionPolicy,omitempty" cborgen:"distributionPolicy,omitempty"`
	Rights             *LiveMetadata_Rights             `json:"rights,omitempty" cborgen:"rights,omitempty"`
	// streamKeyRef: Reference to the stream key (place.stream.key) this metadata applies to.
	StreamKeyRef *comatprototypes.RepoStrongRef `json:"streamKeyRef,omitempty" cborgen:"streamKeyRef,omitempty"`
}

type LiveMetadata_C2pa struct {
	// instanceId: c2pa instance id for this asset, if known.
	InstanceId *string `json:"instanceId,omitempty" cborgen:"instanceId,omitempty"`
	// manifestUrl: where the c2pa manifest can be fetched if not embedded.
	ManifestUrl *string `json:"manifestUrl,omitempty" cborgen:"manifestUrl,omitempty"`
}

// LiveMetadata_DistributionPolicy is a "distributionPolicy" in the place.stream.live.metadata schema.
//
// also emitted as a custom c2pa assertion label: place.stream.distribution/v1
type LiveMetadata_DistributionPolicy struct {
	// allowArchive: Whether viewers can save this stream.
	AllowArchive bool `json:"allowArchive" cborgen:"allowArchive"`
	// allowBroadcast: Whether the content can be rebroadcast.
	AllowBroadcast bool `json:"allowBroadcast" cborgen:"allowBroadcast"`
	// broadcastUntil: How long the stream can be rebroadcast.
	BroadcastUntil string `json:"broadcastUntil" cborgen:"broadcastUntil"`
	// customDuration: Custom end date/time in ISO 8601 format. Required when broadcastUntil is 'custom'.
	CustomDuration *string `json:"customDuration,omitempty" cborgen:"customDuration,omitempty"`
	// policyId: uuid
	PolicyId *string `json:"policyId,omitempty" cborgen:"policyId,omitempty"`
	// policyVersion: e.g. 2025-08-12
	PolicyVersion *string `json:"policyVersion,omitempty" cborgen:"policyVersion,omitempty"`
}

// LiveMetadata_Rights is a "rights" in the place.stream.live.metadata schema.
//
// Content rights and attribution information
type LiveMetadata_Rights struct {
	// attribution: display credit line; maps to photoshop:Credit.
	Attribution *string `json:"attribution,omitempty" cborgen:"attribution,omitempty"`
	// copyright: copyright notice; maps to photoshop:CopyrightNotice.
	Copyright     *string `json:"copyright,omitempty" cborgen:"copyright,omitempty"`
	CopyrightYear *string `json:"copyrightYear,omitempty" cborgen:"copyrightYear,omitempty"`
	// creators: list of creators; maps to dc:creator.
	Creators []string `json:"creators,omitempty" cborgen:"creators,omitempty"`
	// license: ui hint. source of truth is licenseUrl and usageTerms.
	License *string `json:"license,omitempty" cborgen:"license,omitempty"`
	// licenseUrl: canonical license page; maps to xmpRights:WebStatement.
	LicenseUrl *string `json:"licenseUrl,omitempty" cborgen:"licenseUrl,omitempty"`
	// usageTerms: human-readable terms; maps to xmpRights:UsageTerms.
	UsageTerms *string `json:"usageTerms,omitempty" cborgen:"usageTerms,omitempty"`
}
