// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package streamplace

// schema: place.stream.live.metadata

import (
	comatprototypes "github.com/bluesky-social/indigo/api/atproto"
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("place.stream.live.metadata", &LiveMetadata{})
} //
// RECORDTYPE: LiveMetadata
type LiveMetadata struct {
	LexiconTypeID string `json:"$type,const=place.stream.live.metadata" cborgen:"$type,const=place.stream.live.metadata"`
	// contentWarnings: Content warnings for potentially sensitive material based on IPTC standards.
	ContentWarnings []string `json:"contentWarnings,omitempty" cborgen:"contentWarnings,omitempty"`
	// createdAt: When this metadata was created.
	CreatedAt string `json:"createdAt" cborgen:"createdAt"`
	// distributionPolicy: Distribution policy for the livestream content.
	DistributionPolicy *LiveMetadata_DistributionPolicy `json:"distributionPolicy,omitempty" cborgen:"distributionPolicy,omitempty"`
	// livestreamRef: Reference to the livestream this metadata applies to.
	LivestreamRef *comatprototypes.RepoStrongRef `json:"livestreamRef,omitempty" cborgen:"livestreamRef,omitempty"`
	// rights: Content rights and attribution information.
	Rights *LiveMetadata_Rights `json:"rights,omitempty" cborgen:"rights,omitempty"`
}

// LiveMetadata_DistributionPolicy is a "distributionPolicy" in the place.stream.live.metadata schema.
//
// Distribution policy for livestream content
type LiveMetadata_DistributionPolicy struct {
	// allowArchive: Whether viewers can save this stream.
	AllowArchive bool `json:"allowArchive" cborgen:"allowArchive"`
	// allowBroadcast: Whether the content can be rebroadcast.
	AllowBroadcast bool `json:"allowBroadcast" cborgen:"allowBroadcast"`
	// broadcastUntil: How long the stream can be rebroadcast.
	BroadcastUntil string `json:"broadcastUntil" cborgen:"broadcastUntil"`
	// customDuration: Custom end date/time in ISO 8601 format. Required when broadcastUntil is 'custom'.
	CustomDuration *string `json:"customDuration,omitempty" cborgen:"customDuration,omitempty"`
}

// LiveMetadata_Rights is a "rights" in the place.stream.live.metadata schema.
//
// Content rights and attribution information
type LiveMetadata_Rights struct {
	// attribution: How the creator wishes to be credited (name or handle).
	Attribution *string `json:"attribution,omitempty" cborgen:"attribution,omitempty"`
	// copyright: Additional copyright notice or information.
	Copyright *string `json:"copyright,omitempty" cborgen:"copyright,omitempty"`
	// copyrightYear: Copyright year (e.g., 2025).
	CopyrightYear *string `json:"copyrightYear,omitempty" cborgen:"copyrightYear,omitempty"`
	// customLicense: Custom license terms when license is set to 'custom'.
	CustomLicense *string `json:"customLicense,omitempty" cborgen:"customLicense,omitempty"`
	// license: License type for the content. Use 'custom' for non-standard licenses.
	License *string `json:"license,omitempty" cborgen:"license,omitempty"`
}
