// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package streamplace

// schema: place.stream.live.getRecommendations

import (
	"context"

	"github.com/bluesky-social/indigo/lex/util"
)

// LiveGetRecommendations_Output is the output of a place.stream.live.getRecommendations call.
type LiveGetRecommendations_Output struct {
	// streamers: Ordered list of recommended streamer DIDs
	Streamers []string `json:"streamers" cborgen:"streamers"`
	// userDID: The user who created this recommendation list
	UserDID *string `json:"userDID,omitempty" cborgen:"userDID,omitempty"`
}

// LiveGetRecommendations calls the XRPC method "place.stream.live.getRecommendations".
//
// userDID: The DID of the user whose recommendations to fetch
func LiveGetRecommendations(ctx context.Context, c util.LexClient, userDID string) (*LiveGetRecommendations_Output, error) {
	var out LiveGetRecommendations_Output

	params := map[string]interface{}{}
	params["userDID"] = userDID
	if err := c.LexDo(ctx, util.Query, "", "place.stream.live.getRecommendations", params, nil, &out); err != nil {
		return nil, err
	}

	return &out, nil
}
