// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package streamplace

// schema: place.stream.metadata.distributionPolicy

// MetadataDistributionPolicy is a "main" in the place.stream.metadata.distributionPolicy schema.
//
// Distribution and rebroadcast policy.
type MetadataDistributionPolicy struct {
	// deleteAfter: When this stream should be deleted. If not specified, the stream will be kept indefinitely.
	DeleteAfter *string `json:"deleteAfter,omitempty" cborgen:"deleteAfter,omitempty"`
}
