// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package streamplace

// schema: place.stream.metadata.configuration

import (
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("place.stream.metadata.configuration", &MetadataConfiguration{})
} //
// RECORDTYPE: MetadataConfiguration
type MetadataConfiguration struct {
	LexiconTypeID      string                      `json:"$type,const=place.stream.metadata.configuration" cborgen:"$type,const=place.stream.metadata.configuration"`
	ContentRights      *MetadataContentRights      `json:"contentRights,omitempty" cborgen:"contentRights,omitempty"`
	ContentWarnings    *MetadataContentWarnings    `json:"contentWarnings,omitempty" cborgen:"contentWarnings,omitempty"`
	DistributionPolicy *MetadataDistributionPolicy `json:"distributionPolicy,omitempty" cborgen:"distributionPolicy,omitempty"`
}
