// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package streamplace

// schema: place.stream.metadata.distributionPolicy

// MetadataDistributionPolicy is a "main" in the place.stream.metadata.distributionPolicy schema.
//
// Distribution and rebroadcast policy.
type MetadataDistributionPolicy struct {
	// deleteAfter: Duration in seconds after which segments should be deleted. Each segment will expire N seconds after its creation time.
	DeleteAfter *int64 `json:"deleteAfter,omitempty" cborgen:"deleteAfter,omitempty"`
}
